---
site_name: El Carchi
publisher:
  name: Prefectura del Carchi
  address: 
email_addresses:
  from: no-contestar@carchi.gob.ec
  contact: no-contestar@carchi.gob.ec
  proposal_moderators: no-contestar@carchi.gob.ec
  orphan_videos_responsibles: no-contestar@carchi.gob.ec
social_networks:
  twitter: https://twitter.com/GADCarchi
  facebook: https://www.facebook.com/carchiprefectura
  flickr: https://www.facebook.com/carchiprefectura
  youtube: https://www.youtube.com/channel/UCtXoKjyUKo8leh_R227zLQQ
optional_modules:
  proposals: true
  debates: true
  streaming: true
  headlines: true
  customized: true
