---
site_name: El Carchi
publisher:
  name: Prefectura del Carchi
  address: "Calle 10 de Agosto entre Sucre y Olmedo, Tulc√°n"
email_addresses:
  from: no-contestar@carchi.gob.ec
  contact: info@carchi.gob.ec
  proposal_moderators: info@carchi.gob.ec
  orphan_videos_responsibles: info@carchi.gob.ec
social_networks:
  twitter: https://twitter.com/GADCarchi
  facebook: https://www.facebook.com/carchiprefectura
  flickr: https://www.facebook.com/carchiprefectura
  youtube: https://www.youtube.com/channel/UCtXoKjyUKo8leh_R227zLQQ
optional_modules:
  proposals: true
  debates: true
  streaming: true
  headlines: true
  customized: true
customized: true
